baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'Family Recipes'
theme = 'ananke'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About Us'
  url = '/about/'

[[menu.main]]
  identifier = 'search'
  name = 'Search by Ingredient'
  url = '/ingredients/'


[[menu.main]]
  identifier = 'bates'
  name = 'Bates Family Recipes'
  url = '/families/bates'

[[menu.main]]
  identifier = 'pack'
  name = 'Pack Family Recipes'
  url = '/families/pack'

[[menu.main]]
  identifier = 'montgomery'
  name = 'Montgomery Family Recipes'
  url = '/families/montgomery'

[taxonomies]
  family = 'families'
  ingredient = 'ingredients'
  meal = 'meals'
