baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'Family Recipes'
theme = 'ananke'

[params]
  background_color_class = "bg-blue"

[menu]
[[menu.main]]
  identifier = 'a'
  name = 'About Us'
  url = '/about/'
  weight = 20

[[menu.main]]
  identifier = 'b'
  name = 'Search by Ingredient'
  url = '/ingredients/'
  weight = 40

[[menu.main]]
  identifier = 'sbm'
  name = 'Search by Meal'
  url = '/meals/'
  weight = 50


[[menu.main]]
  identifier = 'c'
  name = 'Bates Family Recipes'
  url = '/families/bates'
  weight = 60

[[menu.main]]
  identifier = 'd'
  name = 'Pack Family Recipes'
  url = '/families/pack'
  weight = 80 

[[menu.main]]
  identifier = 'e'
  name = 'Montgomery Family Recipes'
  url = '/families/montgomery'
  weight = 100

[taxonomies]
  family = 'families'
  ingredient = 'ingredients'
  meal = 'meals'

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'ingredients'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
